"""Render a TipTap/ProseMirror memo document to DOCX with citation footnotes.

Footnotes are emitted as numbered superscripts (visually) plus an "Appendix —
Sources" page at the end with full provenance. True Word-style auto-numbered
footnotes in python-docx require XML-level work; we use a numbered-superscript
+ appendix pattern instead, which clients can edit further if they want.
"""

from __future__ import annotations

from io import BytesIO
from typing import Any

from docx import Document
from docx.enum.text import WD_BREAK
from docx.shared import Pt


def _walk_inline(paragraph, content: list[dict[str, Any]]) -> None:
    for node in content or []:
        kind = node.get("type")
        if kind == "text":
            text = node.get("text", "")
            run = paragraph.add_run(text)
            for mark in node.get("marks") or []:
                m = mark.get("type", "")
                if m == "bold":
                    run.bold = True
                elif m == "italic":
                    run.italic = True
                elif m == "underline":
                    run.underline = True
                elif m == "citation":
                    # Render citation as a superscripted inline marker.
                    run.font.superscript = True
                    run.bold = True
        elif kind == "hardBreak":
            paragraph.add_run().add_break()


def _render_node(doc: Document, node: dict[str, Any]) -> None:
    kind = node.get("type")
    if kind == "heading":
        level = int(node.get("attrs", {}).get("level", 1))
        para = doc.add_heading(level=min(max(level, 1), 6))
        _walk_inline(para, node.get("content") or [])
        return
    if kind == "paragraph":
        para = doc.add_paragraph()
        _walk_inline(para, node.get("content") or [])
        return
    if kind == "bulletList":
        for item in node.get("content") or []:
            for child in item.get("content") or []:
                if child.get("type") == "paragraph":
                    para = doc.add_paragraph(style="List Bullet")
                    _walk_inline(para, child.get("content") or [])
        return
    if kind == "orderedList":
        for item in node.get("content") or []:
            for child in item.get("content") or []:
                if child.get("type") == "paragraph":
                    para = doc.add_paragraph(style="List Number")
                    _walk_inline(para, child.get("content") or [])
        return
    # Fallback: attempt to extract any text and put it in a paragraph.
    para = doc.add_paragraph()
    _walk_inline(para, node.get("content") or [])


def render_memo_to_docx(
    *,
    document_json: dict[str, Any],
    title: str,
    sources_appendix: list[dict[str, Any]] | None = None,
    confidential: bool = True,
) -> bytes:
    """Return DOCX bytes for the memo. `sources_appendix` is a list of
    {n, label, url, page, snippet} dicts — printed at the end of the doc."""
    doc = Document()

    # Default font tweak.
    style = doc.styles["Normal"]
    style.font.name = "Calibri"
    style.font.size = Pt(11)

    # Title block.
    title_para = doc.add_heading(level=0)
    run = title_para.add_run(title or "Memo")
    run.bold = True
    if confidential:
        sub = doc.add_paragraph()
        sub_run = sub.add_run("Confidential · Generated by Argus")
        sub_run.italic = True
        sub_run.font.size = Pt(9)

    doc.add_paragraph()  # spacer

    # Walk the ProseMirror tree.
    for node in (document_json or {}).get("content") or []:
        _render_node(doc, node)

    # Appendix.
    if sources_appendix:
        # Page break before sources.
        last = doc.add_paragraph().add_run()
        last.add_break(WD_BREAK.PAGE)
        doc.add_heading("Appendix — Sources", level=1)
        for src in sources_appendix:
            n = src.get("n", "?")
            label = src.get("label", "Source")
            page = src.get("page")
            url = src.get("url")
            snippet = src.get("snippet")
            head = doc.add_paragraph()
            head.add_run(f"[{n}] ").bold = True
            head.add_run(label)
            if page:
                head.add_run(f" — p.{page}").italic = True
            if url:
                small = doc.add_paragraph()
                small.add_run(url).italic = True
            if snippet:
                quote = doc.add_paragraph()
                qrun = quote.add_run(f"“{snippet}”")
                qrun.italic = True
                qrun.font.size = Pt(10)

    buf = BytesIO()
    doc.save(buf)
    return buf.getvalue()
