"""Observability package — Phase 5 / Week 20.

Three modules:

  - :mod:`trace` — contextvars-based trace context (trace_id,
    run_id, session_id, firm_id, actor_id) that propagates across
    async boundaries without threading params through every call
    site.
  - :mod:`logging` — JSON-structured event logger with a hard
    privacy redaction rule (no claim text, no evidence content,
    no memo prose ever lands in logs).
  - :mod:`middleware` — FastAPI middleware that seeds the trace
    context at API entry and logs ``request.start`` /
    ``request.complete`` events.

The pipeline emits structured stage events
(``pipeline.start``, ``planner.complete``, ``retrieval.complete``,
``analyst.complete``, ``verifier.complete``, ``writer.complete``,
``artifacts.generated``, ``pipeline.complete`` /
``pipeline.failed``) carrying the trace_id seeded by the request
middleware (or generated by the pipeline when invoked outside an
HTTP context, e.g. by a Celery worker). One engagement run's full
lifecycle is reconstructable by ``grep trace_id=<id>``.
"""

from .cost import record_cost
from .cost_rollups import (
    EngagementCost,
    FirmCost,
    cost_by_model,
    engagement_cost,
    firm_cost,
    session_cost_total,
)
from .logging import (
    REDACTED_FIELD_NAMES,
    emit_event,
    redact,
    structured_logger,
)
from .metrics import (
    increment,
    observe,
    query_window,
    record_error,
    record_stage_latency,
    render_prometheus,
)
from .trace import (
    TraceContext,
    bind_trace_context,
    get_trace_context,
    new_run_id,
    new_trace_id,
    set_trace_context,
)

__all__ = [
    "EngagementCost",
    "FirmCost",
    "REDACTED_FIELD_NAMES",
    "TraceContext",
    "bind_trace_context",
    "cost_by_model",
    "emit_event",
    "engagement_cost",
    "firm_cost",
    "get_trace_context",
    "increment",
    "new_run_id",
    "new_trace_id",
    "observe",
    "query_window",
    "record_cost",
    "record_error",
    "record_stage_latency",
    "redact",
    "render_prometheus",
    "session_cost_total",
    "set_trace_context",
    "structured_logger",
]
