-- Phase 3 / Week 10 / Day 2: rendered export artifacts.
-- Distinct from the existing `artifacts` table (020_artifacts.sql), which
-- stores editable TipTap engagement documents. This table stores
-- frozen point-in-time renderings (HTML, PDF, PPTX, XLSX, etc.)
-- generated by the export pipeline. If a session's payload changes
-- later (e.g. via section deepening), the existing export_artifact
-- stays frozen; a new generation produces a fresh row.

CREATE TABLE IF NOT EXISTS export_artifacts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    session_id UUID NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    firm_id UUID NOT NULL REFERENCES firms(id),
    artifact_type TEXT NOT NULL,
        -- 'memo' | 'one_pager' | 'deck' | 'excel_model' | 'email' | 'interview_guide'
    format TEXT NOT NULL,
        -- 'html' | 'pdf' | 'pptx' | 'xlsx' | 'docx' | 'md' | 'json'
    payload_snapshot JSONB,
        -- The WriterReportBase payload (consulting_payload) at generation
        -- time. Frozen — never updated after the artifact is rendered.
    file_path TEXT,
        -- Local path under ARGUS_ARTIFACTS_ROOT (default /tmp/argus_artifacts).
        -- Phase 5 swaps for S3/blob storage; the file_path column is the
        -- abstraction.
    file_size_bytes BIGINT,
    claim_citation_count INTEGER DEFAULT 0,
    generation_cost_usd DOUBLE PRECISION DEFAULT 0,
    generation_wall_seconds DOUBLE PRECISION DEFAULT 0,
    generated_by UUID REFERENCES users(id),
    generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    metadata JSONB DEFAULT '{}'::jsonb,
    status TEXT NOT NULL DEFAULT 'generating',
        -- 'generating' | 'ready' | 'failed'
    failure_reason TEXT,
    CONSTRAINT export_artifact_type_format_valid CHECK (
        (artifact_type, format) IN (
            ('memo', 'html'), ('memo', 'pdf'), ('memo', 'docx'),
            ('one_pager', 'html'), ('one_pager', 'pdf'),
            ('deck', 'pptx'), ('deck', 'pdf'),
            ('excel_model', 'xlsx'),
            ('email', 'html'), ('email', 'md'),
            ('interview_guide', 'md'), ('interview_guide', 'pdf')
        )
    ),
    CONSTRAINT export_artifact_status_valid CHECK (
        status IN ('generating', 'ready', 'failed')
    )
);

CREATE INDEX IF NOT EXISTS idx_export_artifacts_session
    ON export_artifacts(session_id, artifact_type, format);
CREATE INDEX IF NOT EXISTS idx_export_artifacts_firm_recent
    ON export_artifacts(firm_id, generated_at DESC);
